### PR TITLE
fix: init variables when drop the beat

### PR DESCRIPTION
**Pull request by clucle**
When drop the beat, the stack is not initialized, only variables are initialized.

Variable UI is not initialized either.

### CODE REVIEW

**Review by lojpark — APPROVED** [review]
LGTM

**Comment by clucle** [comment]
PTAL @lojpark

**Comment by lojpark** [comment]
LGTM😊

**Comment by iubns** [comment]
LGTM

**Review by iubns — COMMENTED** [review]
LGTM thanks!

**Pull request merged**
